/**
 * Downloads the Viactor typefaces from Google Fonts and self-hosts them.
 *
 * Why not a `<link>` to fonts.googleapis.com: a third-party stylesheet in the
 * critical path costs an extra connection plus a render-blocking round trip,
 * and it leaks visitor IPs to Google. Self-hosting fixes both.
 *
 * Google already serves each family split by unicode subset, so downloading
 * only `latin`, `latin-ext`, `cyrillic` and `cyrillic-ext` gives us a correct
 * subset for free, with no fonttools in the build.
 *
 * Run with: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "public", "fonts");
const CSS_PATH = join(ROOT, "src", "styles", "fonts.css");

// A modern desktop UA, or Google serves ttf instead of woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

// Subsets we ship. The audience reads Latin and Cyrillic; Greek and Vietnamese
// would be dead weight.
const KEEP = new Set(["latin", "latin-ext", "cyrillic", "cyrillic-ext"]);

/**
 * `query` is the Google Fonts v2 `family=` value. Axis tags must be listed
 * alphabetically with uppercase before lowercase, or the API 400s.
 */
const FAMILIES = [
  // Viactor design system.
  { slug: "geologica", query: "Geologica:SHRP,wght@0..100,100..900" },
  { slug: "onest", query: "Onest:wght@300..800" },
  { slug: "martian-mono", query: "Martian+Mono:wdth,wght@75..112.5,300..700" },
  // Still used by the not-yet-migrated app pages. Self-hosted here too so the
  // whole site can drop its render-blocking request to fonts.googleapis.com.
  { slug: "dm-sans", query: "DM+Sans:wght@300..500" },
  { slug: "jetbrains-mono", query: "JetBrains+Mono:wght@400" },
];

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`GET ${url} failed: ${res.status}`);
  return res.text();
}

/** Splits a Google Fonts stylesheet into one record per `@font-face` block. */
function parseFaces(css) {
  const faces = [];
  // Each block is preceded by a `/* subset */` comment.
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/gi;
  let match;
  while ((match = re.exec(css)) !== null) {
    const [, subset, body] = match;
    const url = body.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    const weight = body.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
    const stretch = body.match(/font-stretch:\s*([^;]+);/)?.[1]?.trim();
    const style = body.match(/font-style:\s*([^;]+);/)?.[1]?.trim();
    if (url && unicodeRange) {
      faces.push({ subset, url, unicodeRange, weight, stretch, style });
    }
  }
  return faces;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(dirname(CSS_PATH), { recursive: true });

  const blocks = [
    "/*",
    " * GENERATED by scripts/fetch-fonts.mjs. Do not edit by hand.",
    " * Re-run the script to change families, axes or subsets.",
    " */",
    "",
  ];

  for (const { slug, query } of FAMILIES) {
    const sheet = await fetchText(
      `https://fonts.googleapis.com/css2?family=${query}&display=swap`,
    );
    const faces = parseFaces(sheet).filter((f) => KEEP.has(f.subset));
    if (faces.length === 0) throw new Error(`No usable faces for ${query}`);

    const family = decodeURIComponent(query.split(":")[0]).replace(/\+/g, " ");
    blocks.push(`/* ${family} */`);

    for (const face of faces) {
      const file = `${slug}-${face.subset}.woff2`;
      const res = await fetch(face.url, { headers: { "User-Agent": UA } });
      if (!res.ok) throw new Error(`GET ${face.url} failed: ${res.status}`);
      const bytes = Buffer.from(await res.arrayBuffer());
      await writeFile(join(OUT_DIR, file), bytes);
      console.log(`${file.padEnd(34)} ${(bytes.length / 1024).toFixed(1)} KiB`);

      blocks.push(
        "@font-face {",
        `  font-family: "${family}";`,
        `  font-style: ${face.style ?? "normal"};`,
        `  font-weight: ${face.weight ?? "400"};`,
        ...(face.stretch ? [`  font-stretch: ${face.stretch};`] : []),
        "  font-display: swap;",
        `  src: url("/fonts/${file}") format("woff2");`,
        `  unicode-range: ${face.unicodeRange};`,
        "}",
      );
    }
    blocks.push("");
  }

  await writeFile(CSS_PATH, `${blocks.join("\n")}\n`, "utf8");
  console.log(`\nWrote ${CSS_PATH}`);
}

await main();
